/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Codigo.VentanaPrincipal;
import Cola.ColaCircular;
import Excepciones.ColaLlenaException;
import Excepciones.ColaVaciaException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
    private VentanaPrincipal ventana;

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtTamCola = new javax.swing.JTextField();
        BtnTamCola = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnEliminarElemento = new javax.swing.JButton();
        BtnInsertarElemento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtInicioCola = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(160, 355));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Longitud");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 15);
        getContentPane().add(TxtTamCola);
        TxtTamCola.setBounds(10, 70, 50, 20);

        BtnTamCola.setText("Aceptar");
        BtnTamCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTamColaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTamCola);
        BtnTamCola.setBounds(30, 100, 80, 23);

        jLabel2.setText("Elementos de la cola");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 130, 14);

        BtnEliminarElemento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BtnEliminarElemento.setText("-");
        BtnEliminarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarElementoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminarElemento);
        BtnEliminarElemento.setBounds(40, 240, 60, 60);

        BtnInsertarElemento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BtnInsertarElemento.setText("+");
        BtnInsertarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarElementoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsertarElemento);
        BtnInsertarElemento.setBounds(40, 170, 60, 60);

        jLabel3.setText("Crear una cola nueva");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 130, 14);
        getContentPane().add(TxtInicioCola);
        TxtInicioCola.setBounds(80, 70, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Indice inicial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 50, 80, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTamColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTamColaActionPerformed
        int tamCola = Integer.parseInt(getTxtTamCola().getText());
        int inicio = Integer.parseInt(getTxtInicioCola().getText());
        ColaCircular colaNueva = new ColaCircular(inicio, tamCola);
        getVentana().cambiarCola(colaNueva);
    }//GEN-LAST:event_BtnTamColaActionPerformed

    private void BtnInsertarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarElementoActionPerformed
        try {
            int elemento = Integer.parseInt(JOptionPane.showInputDialog("Ingresa un numero"));
            getVentana().getCola().insertar(elemento); 
        }
        catch(ColaLlenaException ex) {
            JOptionPane.showMessageDialog(null, "La cola esta llena", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnInsertarElementoActionPerformed

    private void BtnEliminarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarElementoActionPerformed
        try {
            getVentana().getCola().quitar();            
        }
        catch(ColaVaciaException ex) {
            JOptionPane.showMessageDialog(null, "La cola esta vacia", "ERROR", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_BtnEliminarElementoActionPerformed

    public JButton getBtnEliminarElemento() {
        return BtnEliminarElemento;
    }

    public void setBtnEliminarElemento(JButton BtnEliminarElemento) {
        this.BtnEliminarElemento = BtnEliminarElemento;
    }

    public JButton getBtnInsertarElemento() {
        return BtnInsertarElemento;
    }

    public void setBtnInsertarElemento(JButton BtnInsertarElemento) {
        this.BtnInsertarElemento = BtnInsertarElemento;
    }

    public JButton getBtnTamCola() {
        return BtnTamCola;
    }

    public void setBtnTamCola(JButton BtnTamCola) {
        this.BtnTamCola = BtnTamCola;
    }

    public JTextField getTxtTamCola() {
        return TxtTamCola;
    }

    public void setTxtTamCola(JTextField TxtTamCola) {
        this.TxtTamCola = TxtTamCola;
    }

    public JTextField getTxtInicioCola() {
        return TxtInicioCola;
    }

    public void setTxtInicioCola(JTextField TxtInicioCola) {
        this.TxtInicioCola = TxtInicioCola;
    }

    public VentanaPrincipal getVentana() {
        return ventana;
    }

    public void setVentana(VentanaPrincipal ventana) {
        this.ventana = ventana;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminarElemento;
    private javax.swing.JButton BtnInsertarElemento;
    private javax.swing.JButton BtnTamCola;
    private javax.swing.JTextField TxtInicioCola;
    private javax.swing.JTextField TxtTamCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
